### PR TITLE
ID-440 Create pod spec

### PR DESCRIPTION
**Pull request by mickeylee25**
This PR includes the pod spec

### CODE REVIEW

**Review by phchosis — APPROVED** [review]
Looks good

**Comment by plspalding** [comment]
Have we considered using Combine instead of Rx for this. Maybe not from the start but might be worthing considering going forward.

**Comment by plspalding** [comment]
Also have we considered using Swift Package Manager instead of Cocoa Pods?

**Comment by mickeylee25** [comment]
@plspalding Yes, I remember Jonathon has converted RxSwift to Combine in one of classes in the Mobile SDK and I think it's moved to the Core SDK as well. In terms of the Swift Package Manager, we did the investigation when working on Mobile SDK, but I'm not sure the final reason of using CocoaPods. @phchosis Could you suggest on this?

**Review by plspalding — APPROVED** [review]

**Pull request merged**
